[metadata]
name = DASMC
version = 0.1.0
author = Wentao Yu, Shijia Wang
author_email = yuwt2024@shanghaitech.edu.cn
description = Wait for discription...
long_description = file: README.md
long_description_content_type = text/markdown
url = https://github.com/wentYu/DAphyloSMC
license = GPL-3.0
classifiers =
    Programming Language :: Python :: 3
    License :: OSI Approved :: GNU General Public License v3 (GPLv3)
    Operating System :: OS Independent

[options]
packages = find:
python_requires = >=3.8
include_package_data = True
install_requires =
;     Dendropy==5.0.1
    Dendropy>=4.5.0
;     ete3==3.1.3
    ete3>=3.0.0
;     joblib>=1.3.2
    joblib>=1.0.0
;     matplotlib==3.7.5
    matplotlib>=3.0.0
;     numpy==1.24.4
    numpy>=1.12.0
;     pandas==2.0.3
    pandas>=1.0.0
;     psutil==6.0.0
    psutil>=5.8.0
;     scikit-learn>=1.2.2
    scikit-learn>=0.24.0
;     scipy==1.10.1
    scipy>=1.5.0
;     seaborn==0.13.2
    seaborn>=0.11.0
;     sumt==3.9.0
    sumt>=3.8.0

[options.packages.find]
where = .

[options.package_data]
p4 = *.so, LICENSE

[options.entry_points]
console_scripts =
    dasmc-run = DASMC.SMC:main
    dasmc-train = DASMC.Train:main